services:
  redis:
    image: redis:7.2-bookworm
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1
  elasticsearch:
    build: ./docker/elasticsearch
    image: studioaquatan/elasticsearch-with-kuromoji:8.14.3
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es_data:/usr/share/elasticsearch/data

volumes:
  es_data:
  redis_data: